### ISSUE TITLE
update farm to explicitly link to UniV3 for LPing

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/HOPR-Genesis-DAO#16]
When clicking on the `Become a liquidity provider` button in the currnet [HOPR Farm UI](https://hopr-farm.eth.link/) it opens the Uniswap V3 LP UI (see e.g. the V3 fee tiers in the screenshot below). This should instead directly link to the [V2 LP UI](https://app.uniswap.org/#/pool/v2).

![Screenshot from 2021-05-09 16-30-09](https://user-images.githubusercontent.com/11379673/117575868-e02c5a80-b0e3-11eb-8ed8-1fbdb8335f8c.png)

**Comment by QYuQianchen** [comment]
@SCBuergel Deployed at `QmQonAohPqVfDday6RZWffRdTCBZvRonGd8zXdvPUzbVAT` Please link https://hopr-farm.eth.link/ to the said IPFS CID.

**Comment by SCBuergel** [comment]
https://etherscan.io/tx/0xe1da1994eb6cc90628fb338bd0acc5fbe4196cabc705bac1bd47adc7806b7338
